untitled/book_tracker/config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|uk/ do
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    get 'goals/show'
    get 'goals/edit'
    get 'goals/update'
    get 'profiles/show'
    get 'profiles/edit'
    get 'profiles/update'
    get 'home/index'
    devise_for :users, controllers: { registrations: 'users/registrations' }

    resources :books do
      member do
        post :add_to_list
        post :set_status
      end
      resources :quotes, only: [:create, :destroy]
      resources :notes, only: [:create, :destroy]
    end

    resources :authors, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
      collection do
        get :search
      end
    end

    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
      collection do
        get :search
      end
    end

    resources :book_lists do
      member do
        delete :remove_book_from_list
      end
    end

    resources :achievements, only: [:index]
    resources :reading_calendars, only: [:index]
    resources :recommendations, only: [:index]
    resources :statistics, only: [:index]
    resource :profile, only: [:show, :edit, :update]
    resource :goal, only: [:show, :edit, :update]
    resources :general_library, only: [:index, :show] do
      member do
        post :add_to_my_library, to: 'general_library#add_to_my_library'
      end
    end

    root to: 'profiles#show'
  end
end

untitled/book_tracker/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :user, optional: true
  has_many :book_categories, dependent: :destroy
  has_many :categories, through: :book_categories
  has_many :list_books, dependent: :destroy
  has_many :book_lists, through: :list_books
  has_many :quotes, dependent: :destroy
  has_many :notes, dependent: :destroy

  has_one_attached :cover_image

  validates :title, presence: true
  validates :rating, numericality: { only_integer: true, allow_nil: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }

  scope :general_library, -> { where(user: nil) }

  def add_to_list(list_name)
    list = user.book_lists.find_by(name: list_name)
    return if list.nil?

    list.books << self unless list.books.include?(self)
  end

  def remove_from_list(list_name)
    list = user.book_lists.find_by(name: list_name)
    return if list.nil?

    list.books.delete(self)
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[title description status started_reading_on finished_reading_on rating]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[author book_categories book_lists categories cover_image_attachment cover_image_blob list_books notes quotes user]
  end
end

untitled/book_tracker/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: [:show, :edit, :update, :destroy, :set_status, :add_to_list]
  before_action :set_authors_and_categories, only: [:new, :edit, :create, :update]
  before_action :redirect_to_general_library_if_not_in_user_library, only: [:show]

  def index
    @books = current_user.books
  end

  def show
    @user_lists = current_user.book_lists.where.not(name: ['Хочу прочитать', 'Сейчас читаю', 'Прочитал'])
  end

  def new
    @book = current_user.books.build
  end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      current_user.check_achievements
      redirect_to books_path, notice: 'Book was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      current_user.check_achievements
      redirect_to books_path, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path, notice: 'Book was successfully destroyed.'
  end

  def set_status
    book_status_service = BookStatusService.new(@book, current_user)
    book_status_service.set_status(params)
    redirect_to book_path(@book), notice: 'Status and list were successfully updated.'
  end

  def add_to_list
    book_list_service = BookListService.new(current_user, @book)
    book_list_service.add_to_list(params[:list_name])
    current_user.check_achievements
    redirect_to book_path(@book), notice: 'Book was successfully added to the list.'
  end

  private

  def set_book
    @book = Book.find_by(id: params[:id])
  end

  def set_authors_and_categories
    @authors = Author.all
    @categories = Category.all
  end

  def book_params
    params.require(:book).permit(:title, :description, :cover_image, :author_id, :status, :started_reading_on, :finished_reading_on, :rating, :quotes, :notes, category_ids: [])
  end

  def redirect_to_general_library_if_not_in_user_library
    unless current_user.books.exists?(@book.id)
      redirect_to general_library_path(@book)
    end
  end
end

untitled/book_tracker/app/helpers/books_helper.rb
module BooksHelper
end

untitled/book_tracker/app/views/books/edit.html.erb
<div class="edit-book-form">
  <h1>Edit Book</h1>
  <%= form_for @book, html: { multipart: true } do |f| %>
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :cover_image %>
      <%= f.file_field :cover_image %>
    </div>
    <div class="field">
      <%= f.label :author_id, 'Author' %>
      <input type="text" id="author-search" placeholder="Search for authors...">
      <ul id="author-search-results"></ul>
      <ul id="selected-author">
        <% if @book.author %>
          <li data-id="<%= @book.author.id %>"><%= @book.author.name %> <button type="button" class="remove-author">Remove</button></li>
        <% end %>
      </ul>
      <input type="hidden" name="book[author_id]" id="author-id" value="<%= @book.author_id %>">
    </div>
    <div class="field">
      <%= f.label :category_ids, 'Categories' %>
      <input type="text" id="category-search" placeholder="Search for categories...">
      <ul id="category-search-results"></ul>
      <ul id="selected-categories">
        <% @book.categories.each do |category| %>
          <li data-id="<%= category.id %>"><%= category.name %> <button type="button" class="remove-category">Remove</button></li>
        <% end %>
      </ul>
      <input type="hidden" name="book[category_ids][]" id="category-ids" multiple="true">
    </div>
    <div class="actions">
      <%= f.submit 'Update Book' %>
    </div>
  <% end %>
</div>

<script>
    document.addEventListener('DOMContentLoaded', () => {
        const authorSearch = document.getElementById('author-search');
        const authorSearchResults = document.getElementById('author-search-results');
        const selectedAuthor = document.getElementById('selected-author');
        const authorIdInput = document.getElementById('author-id');

        authorSearch.addEventListener('input', () => {
            const query = authorSearch.value;
            if (query.length < 2) {
                authorSearchResults.innerHTML = '';
                return;
            }

            fetch(`/authors?query=${query}`, {
                headers: {
                    'Accept': 'application/json'
                }
            })
              .then(response => response.json())
              .then(data => {
                  authorSearchResults.innerHTML = '';
                  if (data.length === 0) {
                      const createAuthorLi = document.createElement('li');
                      createAuthorLi.textContent = `Создать "${query}"`;
                      createAuthorLi.addEventListener('click', () => {
                          createAuthor(query);
                      });
                      authorSearchResults.appendChild(createAuthorLi);
                  } else {
                      data.forEach(author => {
                          const li = document.createElement('li');
                          li.textContent = author.name;
                          li.dataset.id = author.id;
                          li.addEventListener('click', () => {
                              selectAuthor(author.id, author.name);
                          });
                          authorSearchResults.appendChild(li);
                      });
                  }
              });
        });

        selectedAuthor.addEventListener('click', (event) => {
            if (event.target.classList.contains('remove-author')) {
                const li = event.target.parentElement;
                selectedAuthor.removeChild(li);
                authorIdInput.value = '';
            }
        });

        function selectAuthor(id, name) {
            selectedAuthor.innerHTML = '';
            const selectedLi = document.createElement('li');
            selectedLi.textContent = name;
            selectedLi.dataset.id = id;
            const removeButton = document.createElement('button');
            removeButton.type = 'button';
            removeButton.textContent = 'Remove';
            removeButton.addEventListener('click', () => {
                selectedAuthor.removeChild(selectedLi);
                authorIdInput.value = '';
            });
            selectedLi.appendChild(removeButton);
            selectedAuthor.appendChild(selectedLi);
            authorIdInput.value = id;
            authorSearch.value = '';
            authorSearchResults.innerHTML = '';
        }

        function createAuthor(name) {
            fetch('/authors', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Accept': 'application/json',
                    'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
                },
                body: JSON.stringify({ author: { name: name, bio: 'Default bio' } })
            })
              .then(response => response.json())
              .then(data => {
                  if (data.id) {
                      selectAuthor(data.id, data.name);
                  } else {
                      alert('Error creating author: ' + data.errors.join(', '));
                  }
              });
        }

        const categorySearch = document.getElementById('category-search');
        const categorySearchResults = document.getElementById('category-search-results');
        const selectedCategories = document.getElementById('selected-categories');
        const categoryIdsInput = document.getElementById('category-ids');

        categorySearch.addEventListener('input', () => {
            const query = categorySearch.value;
            if (query.length < 2) {
                categorySearchResults.innerHTML = '';
                return;
            }

            fetch(`/categories?query=${query}`, {
                headers: {
                    'Accept': 'application/json'
                }
            })
              .then(response => response.json())
              .then(data => {
                  categorySearchResults.innerHTML = '';
                  if (data.length === 0) {
                      const createCategoryLi = document.createElement('li');
                      createCategoryLi.textContent = `Создать "${query}"`;
                      createCategoryLi.addEventListener('click', () => {
                          createCategory(query);
                      });
                      categorySearchResults.appendChild(createCategoryLi);
                  } else {
                      data.forEach(category => {
                          const li = document.createElement('li');
                          li.textContent = category.name;
                          li.dataset.id = category.id;
                          li.addEventListener('click', () => {
                              selectCategory(category.id, category.name);
                          });
                          categorySearchResults.appendChild(li);
                      });
                  }
              });
        });

        selectedCategories.addEventListener('click', (event) => {
            if (event.target.classList.contains('remove-category')) {
                const li = event.target.parentElement;
                selectedCategories.removeChild(li);
                updateCategoryIds();
            }
        });

        function selectCategory(id, name) {
            if (!Array.from(selectedCategories.children).find(child => child.dataset.id == id)) {
                const selectedLi = document.createElement('li');
                selectedLi.textContent = name;
                selectedLi.dataset.id = id;
                const removeButton = document.createElement('button');
                removeButton.type = 'button';
                removeButton.textContent = 'Remove';
                removeButton.addEventListener('click', () => {
                    selectedCategories.removeChild(selectedLi);
                    updateCategoryIds();
                });
                selectedLi.appendChild(removeButton);
                selectedCategories.appendChild(selectedLi);
                updateCategoryIds();
                categorySearch.value = '';
                categorySearchResults.innerHTML = '';
            }
        }

        function createCategory(name) {
            fetch('/categories', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Accept': 'application/json',
                    'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
                },
                body: JSON.stringify({ category: { name: name } })
            })
              .then(response => response.json())
              .then(data => {
                  if (data.id) {
                      selectCategory(data.id, data.name);
                  } else {
                      alert('Error creating category: ' + data.errors.join(', '));
                  }
              });
        }

        function updateCategoryIds() {
            const ids = Array.from(selectedCategories.children).map(li => li.dataset.id);
            while (categoryIdsInput.firstChild) {
                categoryIdsInput.removeChild(categoryIdsInput.firstChild);
            }
            ids.forEach(id => {
                const hiddenField = document.createElement('input');
                hiddenField.type = 'hidden';
                hiddenField.name = 'book[category_ids][]';
                hiddenField.value = id;
                categoryIdsInput.appendChild(hiddenField);
            });
        }

        updateCategoryIds();
    });
</script>

untitled/book_tracker/app/views/books/index.html.erb
<div class="library">
  <h1><%= t('library.my_library') %></h1>
  <div class="header-buttons">
    <%= link_to new_book_path, class: 'add-book-button' do %>
      <%= image_tag 'add_new_book.png', size: '40x40', alt: t('library.add_book') %>
    <% end %>
    <%= link_to recommendations_path, class: 'recommendations-button' do %>
      <%= image_tag 'rec.png', size: '40x40', alt: t('library.recommendations') %>
    <% end %>
  </div>
  <div class="books-list">
    <% @books.each do |book| %>
      <div class="book-card">
        <%= image_tag book.cover_image.attached? ? url_for(book.cover_image) : 'default_cover.png', size: "150x200" %>
        <%= link_to book.title, book_path(book) %>
      </div>
    <% end %>
  </div>
</div>

untitled/book_tracker/app/views/books/show.html.erb
<div class="book-details">
  <div class="action-buttons">
    <%= link_to edit_book_path(@book), class: 'edit-button' do %>
      <img src="<%= asset_path('edit_book.png') %>" alt="<%= t('library.edit_book') %>">
    <% end %>
    <%= form_with model: @book, method: :delete, local: true, class: 'delete-button' do %>
      <button type="submit" data-confirm="<%= t('library.confirm_delete') %>">
        <img src="<%= asset_path('delete_book.png') %>" alt="<%= t('library.delete_book') %>">
      </button>
    <% end %>
  </div>

  <h1><%= @book.title %></h1>
  <%= image_tag @book.cover_image.attached? ? url_for(@book.cover_image) : 'default_cover.png', size: "300x400" %>
  <p class="description"><%= @book.description %></p>
  <p class="author"><%= t('library.author') %>: <%= link_to @book.author.name, author_path(@book.author) %></p>
  <p class="categories"><%= t('library.categories') %>: <%= @book.categories.map { |category| link_to category.name, category_path(category) }.join(', ').html_safe %></p>
  <p class="rating"><%= t('library.rating') %>: <%= @book.rating %></p>

  <div class="form-container">
    <div class="status-form">
      <h2><%= t('library.set_status') %></h2>
      <%= form_with url: set_status_book_path(@book), method: :post, local: true do %>
        <%= select_tag :status, options_for_select(['Хочу прочитать', 'Сейчас читаю', 'Прочитал'], selected: @book.status || 'Сейчас читаю') %>
        <div id="reading-dates" style="display: none;">
          <%= label_tag :started_reading_on, t('library.started_reading_on') %>
          <%= date_field_tag :started_reading_on, @book.started_reading_on %>
          <%= label_tag :finished_reading_on, t('library.finished_reading_on') %>
          <%= date_field_tag :finished_reading_on, @book.finished_reading_on %>
          <%= label_tag :rating, t('library.rating') %>
          <%= select_tag :rating, options_for_select((1..10).to_a, selected: @book.rating) %>
        </div>
        <%= submit_tag t('library.set_status') %>
      <% end %>
    </div>

    <div class="add-to-list-form">
      <h2><%= t('library.add_to_list') %></h2>
      <%= form_with url: add_to_list_book_path(@book), method: :post, local: true do %>
        <%= select_tag :list_name, options_for_select(@user_lists.map(&:name)) %>
        <%= submit_tag t('library.add_to_list') %>
      <% end %>
    </div>
  </div>

  <div class="section-container">
    <div class="section">
      <h2><%= t('library.quotes') %></h2>
      <button type="button" onclick="toggleSection('quotes-section')"><%= t('library.show_hide', section: t('library.quotes')) %></button>
      <div id="quotes-section" class="section-content">
        <% @book.quotes.each do |quote| %>
          <p><%= quote.content %> <em><%= quote.created_at.strftime('%Y-%m-%d') %></em></p>
          <%= form_with model: [@book, quote], url: book_quote_path(@book, quote), method: :delete, local: true do %>
            <button type="submit" class="new-remove-button" data-confirm="<%= t('library.confirm_delete') %>"><%= t('library.remove') %></button>
          <% end %>
        <% end %>
        <%= form_with model: [@book, @book.quotes.build], local: true do |f| %>
          <%= f.text_area :content, placeholder: t('library.add_new', item: t('library.quotes').singularize) %>
          <%= f.submit t('library.add_quote'), class: 'submit-button' %>
        <% end %>
      </div>
    </div>

    <div class="section">
      <h2><%= t('library.notes') %></h2>
      <button type="button" onclick="toggleSection('notes-section')"><%= t('library.show_hide', section: t('library.notes')) %></button>
      <div id="notes-section" class="section-content">
        <% @book.notes.each do |note| %>
          <p><%= note.content %> <em><%= note.created_at.strftime('%Y-%m-%d') %></em></p>
          <%= form_with model: [@book, note], url: book_note_path(@book, note), method: :delete, local: true do %>
            <button type="submit" class="new-remove-button" data-confirm="<%= t('library.confirm_delete') %>"><%= t('library.remove') %></button>
          <% end %>
        <% end %>
        <%= form_with model: [@book, @book.notes.build], local: true do |f| %>
          <%= f.text_area :content, placeholder: t('library.add_new', item: t('library.notes').singularize) %>
          <%= f.submit t('library.add_note'), class: 'submit-button' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', () => {
        const statusSelect = document.querySelector('select[name="status"]');
        const readingDates = document.getElementById('reading-dates');

        const toggleReadingDates = () => {
            if (statusSelect.value === 'Прочитал') {
                readingDates.style.display = 'block';
            } else {
                readingDates.style.display = 'none';
            }
        };

        statusSelect.addEventListener('change', toggleReadingDates);
        toggleReadingDates();
    });

    function toggleSection(sectionId) {
        const section = document.getElementById(sectionId);
        section.style.display = section.style.display === 'none' ? 'block' : 'none';
    }
</script>