untitled/book_tracker/config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|uk/ do
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    get 'goals/show'
    get 'goals/edit'
    get 'goals/update'
    get 'profiles/show'
    get 'profiles/edit'
    get 'profiles/update'
    get 'home/index'
    devise_for :users, controllers: { registrations: 'users/registrations' }

    resources :books do
      member do
        post :add_to_list
        post :set_status
      end
      resources :quotes, only: [:create, :destroy]
      resources :notes, only: [:create, :destroy]
    end

    resources :authors, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
      collection do
        get :search
      end
    end

    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
      collection do
        get :search
      end
    end

    resources :book_lists do
      member do
        delete :remove_book_from_list
      end
    end

    resources :achievements, only: [:index]
    resources :reading_calendars, only: [:index]
    resources :recommendations, only: [:index]
    resources :statistics, only: [:index]
    resource :profile, only: [:show, :edit, :update]
    resource :goal, only: [:show, :edit, :update]
    resources :general_library, only: [:index, :show] do
      member do
        post :add_to_my_library, to: 'general_library#add_to_my_library'
      end
    end

    root to: 'profiles#show'
  end
end

untitled/book_tracker/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :authenticate_user!

  def show
  end

  def edit
  end

  def update
    if current_user.update(goal_params)
      redirect_to goal_path, notice: 'Goal was successfully updated.'
    else
      render :edit
    end
  end

  private

  def goal_params
    params.require(:user).permit(:reading_goal)
  end
end

untitled/book_tracker/app/helpers/goals_helper.rb
module GoalsHelper
end

untitled/book_tracker/app/views/goals/edit.html.erb
<div class="edit-goal-page">
  <h1><%= t('goal.edit_goal') %></h1>

  <%= form_with model: current_user, url: goal_path, method: :patch do |f| %>
    <div class="field">
      <%= f.label :reading_goal, t('goal.goal_number_of_books') %>
      <%= f.number_field :reading_goal %>
    </div>
    <div class="actions">
      <%= f.submit t('goal.update_goal') %>
    </div>
  <% end %>
</div>

untitled/book_tracker/app/views/goals/show.html.erb
<div class="goal-page">
  <%= link_to edit_goal_path, class: 'edit-goal' do %>
    <img src="<%= asset_path('edit.png') %>" alt="<%= t('goal.edit_goal') %>">
  <% end %>

  <div class="goal">
    <%= t('goal.goal_for_year', year: Time.current.year) %>: <%= current_user.reading_goal || t('goal.not_set') %> books
    <div class="goal-subtitle">
      <%= t('goal.books_read_this_year') %>: <%= current_user.books_read_count_this_year %> / <%= current_user.reading_goal %>
    </div>
  </div>

  <div class="progress-container">
    <div class="progress-bar">
      <div class="progress-bar-fill" style="width: <%= current_user.goal_progress %>%;">
        <span class="percentage"><%= current_user.goal_progress %>%</span>
      </div>
    </div>
  </div>

  <h2><%= t('goal.books_read') %>:</h2>
  <ul>
    <% current_user.books_read_this_year.each do |book| %>
      <li>
        <%= link_to book.title, book_path(book) %>
        <p><%= t('goal.started_on') %>: <%= book.started_reading_on %>, <%= t('goal.finished_on') %>: <%= book.finished_reading_on %></p>
      </li>
    <% end %>
  </ul>
</div>

untitled/book_tracker/app/views/goals/update.html.erb
<h1>Goals#update</h1>
<p>Find me in app/views/goals/update.html.erb</p>