untitled/book_tracker/config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|uk/ do
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    get 'goals/show'
    get 'goals/edit'
    get 'goals/update'
    get 'profiles/show'
    get 'profiles/edit'
    get 'profiles/update'
    get 'home/index'
    devise_for :users, controllers: { registrations: 'users/registrations' }

    resources :books do
      member do
        post :add_to_list
        post :set_status
      end
      resources :quotes, only: [:create, :destroy]
      resources :notes, only: [:create, :destroy]
    end

    resources :authors, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
      collection do
        get :search
      end
    end

    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
      collection do
        get :search
      end
    end

    resources :book_lists do
      member do
        delete :remove_book_from_list
      end
    end

    resources :achievements, only: [:index]
    resources :reading_calendars, only: [:index]
    resources :recommendations, only: [:index]
    resources :statistics, only: [:index]
    resource :profile, only: [:show, :edit, :update]
    resource :goal, only: [:show, :edit, :update]
    resources :general_library, only: [:index, :show] do
      member do
        post :add_to_my_library, to: 'general_library#add_to_my_library'
      end
    end

    root to: 'profiles#show'
  end
end

untitled/book_tracker/app/models/author.rb
class Author < ApplicationRecord
  has_many :books

  def self.ransackable_attributes(auth_object = nil)
    %w[bio created_at id name updated_at]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[books]
  end
end

untitled/book_tracker/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query]
      @authors = Author.where('name LIKE ?', "%#{params[:query]}%")
    else
      authors = Author.all
    end

    respond_to do |format|
      format.html
      format.json { render json: authors_as_json }
    end
  end

  def show
    @general_library_books = @author.books.where(general_library: true)
    @user_library_books = current_user.books.where(author: @author)
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      render json: { id: @author.id, name: @author.name }
    else
      render json: { errors: @author.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @author.update(author_params)
      redirect_to authors_path, notice: 'Author was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @author.destroy
    redirect_to authors_path, notice: 'Author was successfully destroyed.'
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:name, :bio)
  end

  def authors_as_json
    authors = if params[:query]
                Author.where('name LIKE ?', "%#{params[:query]}%")
              else
                Author.all
              end
    authors.map { |author| { id: author.id, name: author.name } }
  end
end

untitled/book_tracker/app/helpers/authors_helper.rb
module AuthorsHelper
end

untitled/book_tracker/app/views/authors/edit.html.erb
<h1>Edit Author</h1>
<%= form_for @author do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>
  <div class="actions">
    <%= f.submit 'Update Author' %>
  </div>
<% end %>
<%= link_to 'Back to Authors', authors_path %>

untitled/book_tracker/app/views/authors/index.html.erb
<h1>Authors</h1>
<%= link_to 'Add New Author', new_author_path %>
<ul>
  <% authors.each do |author| %>
    <li>
      <%= author.name %>
      <%= link_to 'Edit', edit_author_path(author) %>
      <%= link_to 'Delete', author_path(author), method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>
<%= link_to 'Back to Library', books_path %>

untitled/book_tracker/app/views/authors/new.html.erb
<h1>New Author</h1>
<%= form_for @author do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Author' %>
  </div>
<% end %>
<%= link_to 'Back to New Book', new_book_path %>

untitled/book_tracker/app/views/authors/show.html.erb
<div class="author-page">
  <h1><%= @author.name %></h1>
  <p><%= @author.bio %></p>

  <h2>Books by this author in My Library:</h2>
  <ul>
    <% @user_library_books.each do |book| %>
      <li>
        <%= image_tag book.cover_image.attached? ? url_for(book.cover_image) : 'default_cover.png', size: "100x150" %>
        <%= link_to book.title, book_path(book) %>
      </li>
    <% end %>
  </ul>

  <h2>Books by this author in General Library:</h2>
  <ul>
    <% @general_library_books.each do |book| %>
      <li>
        <%= image_tag book.cover_image.attached? ? url_for(book.cover_image) : 'default_cover.png', size: "100x150" %>
        <%= link_to book.title, general_library_path(book) %>
      </li>
    <% end %>
  </ul>
</div>